CHECKPOINT_DIR: "ndt_runs/"
DATA:
  DATAPATH: "path/to/MC_Maze_standard/"
  # TRAIN_FILENAME: 'MC_Maze/mc_maze_behavior_fp.h5' #! no FP
  # VAL_FILENAME: 'MC_Maze/mc_maze_behavior_fp.h5' #! no FP
  # IGNORE_FORWARD: True #! no FP
  TRAIN_FILENAME: 'MC_Maze/mc_maze_behavior_fp_behavior.h5' #! FP
  VAL_FILENAME: 'MC_Maze/mc_maze_behavior_fp_behavior.h5' #! FP
  IGNORE_FORWARD: False #! FP
MODEL:
  NAME: 'NeuralDataTransformer'
  TRIAL_LENGTH: 0 # 140
  LEARNABLE_POSITION: True
  PRE_NORM: True
  FIXUP_INIT: True
  EMBED_DIM: 0
  LOGRATE: True
  NUM_LAYERS: 4
TRAIN:
  DISTILLATION: True
  DISTILLATION_ALPHA: 0.5
  LR:
    WARMUP: 2000 # original 5000
    INIT: 5.0e-5
  MASK_RATIO: 0.25
  WEIGHT_DECAY: 5.0e-05
  PATIENCE: 3000
  # PATIENCE: 10000
  LOG_INTERVAL: 200
  VAL_INTERVAL: 20
  CHECKPOINT_INTERVAL: 1000
  NUM_UPDATES: 50501 # epochs
  MASK_SPAN_RAMP_START: 8000
  MASK_SPAN_RAMP_END: 12000

  TUNE_HP_JSON: './configs/mc_maze.json' # This space has more aggressive regularization
